LOG:
  DIR: "./log/"
  LEVEL: "DEBUG"

CAMERA:
  ID: 0
  FPS: 30
  SIZE_X: 640
  SIZE_Y: 480
  RESIZE_X: 640
  RESIZE_Y: 480

  FULLSCREEN: False

KEY:
  PATH: "../resource/key/regi_key.json"
  NUM: 2
  COUNT: 3
  CLASS: "yolov5_module/data/coco128.yaml"